### ISSUE TITLE
Support for `cargo install --git <url>`

### ISSUE THREAD

**Issue by EtaoinWu** [baptiste0928/cargo-install#13]
Hi, I'd like to install Rust projects that are on github but not on crate.io.

To be specific, projects like `iden3/circom` [on github](https://github.com/iden3/circom) are [not uploaded to crate.io](https://github.com/iden3/circom/issues/40). I can install them with `cargo install --git <url>` without caching, and it's possible to fetch the github API to check the repo's latest tag/release for caching.

**Comment by baptiste0928** [comment]
Hi, thanks for the suggestion. This is definitely a use case that could be implemented.

`cargo` supports installing from git with a specific branch, commit or tag. The last two can be used directly for the cache key (although tags can be moved to another commit, this is rarely the case). For branches, I can easily get the commit hash from the [GitHub API](https://docs.github.com/en/rest/branches/branches#list-branches), but I can also try using [`git ls-remote`](https://git-scm.com/docs/git-ls-remote) to be compatible with *any* git repository.

For the default behavior without a specific commit/tag/branch, I hesitate between using the latest commit from the default branch or a "smarter" strategy (latest release, or latest tag if unavailable). But the latter doesn't follow the `cargo install` behavior I'm trying to mimic, since this action should be a drop-in replacement for uncached `cargo install` commands.

What do you think?

**Comment by baptiste0928** [comment]
I've implemented this in #14. Can you test if everything works for you before I merge it?

You can use the PR's branch like this:
```yaml
-  uses: baptiste0928/cargo-install@feat/git-install
   with:
    crate: circom  # required even for git installation (used in cache key and logs)
    git: https://github.com/iden3/circom
    tag: v2.1.5 # optional, rev/branch also supported
```

Let me know if it works or if run into any issue.
