### ISSUE TITLE
Add support for `--registry` and `--index` parameters

### ISSUE THREAD

**Issue by Veetaha** [baptiste0928/cargo-install#15]
For the use case when the installation happens from an alternative crates registry (e.g. a registry like Cloudsmith) `cargo install` provides a `--registry` and `--index` parameters.

It should be simple to provide a way to pass a `registry` and `index` input parameters for the action. It's important that the values of these parameters is then used in the cache key. 

These parameters are mutually exclusive. The `--registry` is just a named index. I.e. the user has to have the following in the config.
```toml
[registries.registry-name]
index = "URL"
```

I am not sure how hard it will be to support version wildcards with alternative registries. I suppose listing the registry isn't included in [the registry web API requirements](https://doc.rust-lang.org/cargo/reference/registry-web-api.html). It would be at least something if only exact versions are supported for alternative registries

**Comment by baptiste0928** [comment]
I'm not familiar with alternative registries, but implementing version resolution as currently done with crates.io will not be possible without an easy way to query all available versions.

This might be possible with sparse indexes, but not all registries support them, and even then it will require parsing the [index configuration](https://doc.rust-lang.org/cargo/reference/registry-index.html#index-configuration) and [registry configuration](https://doc.rust-lang.org/cargo/reference/registries.html#using-an-alternate-registry).

For now, the best option is - as you suggested - to support only exact version requirements. I'll try to find some time to implement this in the next few days.

If supporting version wildcards is a requirement for some use cases, you can always use a more generic caching action like the awesome [`swatinem/rust-cache` action](https://github.com/Swatinem/rust-cache), but the cache will be invalidated more often and will not be invalidated when a new version matching the requirements is available.

**Comment by baptiste0928** [comment]
Hey @Veetaha, I've implemented this in #18. Can you test if everything works for you before I merge it?

You can use the PR's branch like this:
```yaml
-  uses: baptiste0928/cargo-install@feat/custom-registry
   with:
    crate: my-awesome-crate
    version: 1.0.0 # exact version, except if using sparse index
    # index or registry parameters
```

Let me know if it works or if run into any issue.

**Comment by Veetaha** [comment]
Hey, I gave it a test run with the following setup (I redacted the names, since it uses a private registry):

```yaml
uses: baptiste0928/cargo-install@b3ea78257dd2498a1656a5faa4aabbff8e287fd1
with:
  args: --bin bin-name
  crate: package-name
  index: https://dl.cloudsmith.io/basic/org-name/repo-name/cargo/index.git
```

This failed with the following output

```
Installing crate-name...
  Error: Version ranges can only be used with sparse indexes
```

Then I tried specifying an exact version and it worked
```yaml
uses: baptiste0928/cargo-install@b3ea78257dd2498a1656a5faa4aabbff8e287fd1
with:
  args: --bin bin-name
  crate: package-name
  index: https://dl.cloudsmith.io/basic/org-name/repo-name/cargo/index.git
  version: x.y.z
```

```
Installing crate-name...
  Using non-sparse index, skipping version resolution
  Installation settings:
     version: x.y.z
     path: /home/runner/.cargo-install/crate-name
     key: cargo-install-crate-name-x.y.z-1f65051c7c713cc24cf4
No cached version found, installing crate-name using cargo...
Added /home/runner/.cargo-install/crate-name/bin to PATH.
Installed crate-name x.y.z.
```

But would it be possible to support the use case at the top where the version is not specified? Meaning it should install just the latest version? I suppose there will be a problem of setting the cache key since no version is known at this point?
