### ISSUE TITLE
Support for no-default-features

### ISSUE THREAD

**Issue by sunshowers** [baptiste0928/cargo-install#3]
Hi again :)

For [cargo-nextest](https://nexte.st/book/installing-from-source.html), I'd like to recommend folks install it with `--no-default-features` in CI. The default set of features includes self-update functionality that isn't relevant in CI. Would it be possible to add that? Maybe as a `default-features: false` parameter, similar to `Cargo.toml`.

**Comment by baptiste0928** [comment]
Hello! I just released v1.3.0 with a new `args` input to add custom arguments to the `cargo install` command.

```yaml
- name: Install cargo-nextest
  uses: baptiste0928/cargo-install@v1
  with:
    crate: cargo-nextest
    args: --no-default-features
 ```
