### ISSUE TITLE
Short-lived caching

### ISSUE THREAD

**Issue by pronebird** [baptiste0928/cargo-install#31]
Hi,

I have noticed that caching is very short lived. I have installed `sqlx` 10 days ago, ran the same workflow today and noticed that it keeps building a fresh copy of `sqlx` for no good reason. This is my workflow step(s):

```yml
- name: Detect sqlx version
  id: detect-sqlx
  run: |
    SQLX_VERSION=$(cargo metadata --format-version 1 | jq -r '.packages[] | select (.name == "sqlx") | .version')
    echo "SQLX_VERSION=$SQLX_VERSION" >> $GITHUB_OUTPUT

- name: Install sqlx-cli v${{ steps.detect-sqlx.outputs.SQLX_VERSION }}
  uses: baptiste0928/cargo-install@91c5da15570085bcde6f4d7aed98cb82d6769fd3
  env:
    RUSTFLAGS: -C target-feature=+crt-static
    CARGO_BUILD_TARGET: x86_64-unknown-linux-gnu
  with:
    crate: sqlx-cli
    version: ${{ steps.detect-sqlx.outputs.SQLX_VERSION }}
    cache-key: sqlx-${{ steps.detect-sqlx.outputs.SQLX_VERSION }}-static-crt
```

The sqlx version remains the same (i.e 0.8.3). How can I tweak the retention duration?
