### ISSUE TITLE
Cache does not work: "reserveCache failed: Cache service responded with 503" on GitHub Actions

### ISSUE THREAD

**Issue by enomoto11** [baptiste0928/cargo-install#32]
Hi, thank you for your great action!

I am using `baptiste0928/cargo-install@v2` in my GitHub Actions workflow, but the cache feature never works.  
Every time, I see the following log and the cache is not saved:

```
warning: be sure to add `/home/runner/.cargo-install/cargo-nextest/bin` to your PATH to be able to run the installed binaries
/usr/bin/tar --posix -cf cache.tzst --exclude cache.tzst -P -C /home/runner/work/my-project/my-project --files-from manifest.txt --use-compress-program zstdmt
Warning: Failed to save: reserveCache failed: Cache service responded with 503
```

**Steps to reproduce:**
1. Use the following step in a GitHub Actions workflow:
    ```yaml
    - name: Install cargo-nextest
      uses: baptiste0928/cargo-install@v2
      with:
        crate: cargo-nextest
    ```
2. Run the workflow.
3. The above 503 error occurs every time, and the cache is never saved.

**Environment:**
- GitHub Actions: `ubuntu-latest`
- `baptiste0928/cargo-install@v2`
- Other cache actions (e.g., `Swatinem/rust-cache@v2`) work fine in the same workflow.

**Questions:**
- Do you know what could be causing the 503 error from the cache service? (Is it a rate limit, cache size, or something else?)
- If it is related to cache size, I am not sure how to debug or check the actual cache size being uploaded.  
  Do you have any recommended way to investigate or debug this?
- Is there any workaround or recommended solution?

**References:**
- [actions/cache documentation](https://github.com/actions/cache)
- [cargo-install@v2 README](https://github.com/baptiste0928/cargo-install)

Thank you in advance for your help!

**Comment by baptiste0928** [comment]
Hi! The `v2` version uses a [deprecated cache API](https://github.com/actions/toolkit/discussions/1890) that has stopped working. You need to use the `v3` version of the action:
 
```yaml
- name: Install cargo-nextest
  uses: baptiste0928/cargo-install@v3
  with:
    crate: cargo-nextest
```
