### ISSUE TITLE
Support installing multiple crates at once

### ISSUE THREAD

**Issue by brainstorm** [baptiste0928/cargo-install#4]
See https://github.com/umccr/reusable-github-actions/commit/8f8f0537233777825a06fc6ec540e0b7684206a1 for more context.

```yaml
- name: Install several audit crates
  uses: baptiste0928/cargo-install@v1
  with:
    crate: 
       - cargo-deny
       - cargo-udeps
       - cargo-outdated
       - cargo-pants
       - cargo-audit
```
